# Generated by Django 5.1.5 on 2025-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_address', models.CharField(max_length=500)),
                ('actual_address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('director_name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('ogrn', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
