# Generated by Django 5.1.5 on 2025-02-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации полное')),
                ('shortname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации сокращенное')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=12, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, null=True, verbose_name='Фактический адрес')),
                ('checking_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет')),
                ('namebank', models.TextField(blank=True, null=True, verbose_name='Название банка')),
                ('bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('website', models.CharField(blank=True, max_length=20, null=True, verbose_name='Сайт')),
                ('accreditation_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер записи об аккредитации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
