# Generated by Django 5.1.5 on 2025-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='director_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='accreditation_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер записи об аккредитации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bik',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='organization',
            name='checking_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='organization',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='organization',
            name='namebank',
            field=models.TextField(blank=True, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='organization',
            name='shortname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации сокращенное'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='actual_address',
            field=models.TextField(blank=True, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации полное'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
