# Generated by Django 5.1.5 on 2025-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fio_director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя лаборатории'),
        ),
    ]
