# Generated by Django 5.1.5 on 2025-02-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.TextField(blank=True, choices=[('measurement_tool', 'Средство измерения'), ('testing_equipment', 'Испытательное оборудование'), ('auxiliary_equipment', 'Вспомогательное оборудование')], null=True, verbose_name='Тип оборудования')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Наименование, модель')),
                ('tip', models.TextField(blank=True, null=True, verbose_name='Тип')),
                ('zav_nomer', models.TextField(blank=True, null=True, verbose_name='Заводской №')),
                ('inv_nomer', models.TextField(blank=True, null=True, verbose_name='Инв. №, год ввода в эксплуатацию')),
                ('reg_nomer', models.TextField(blank=True, null=True, verbose_name='Регистрационный номер СИ в Госреестре СИ')),
                ('kol_vo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во')),
                ('klass_toch', models.TextField(blank=True, null=True, verbose_name='Класс точности, погрешность /ТТХ')),
                ('predel', models.TextField(blank=True, null=True, verbose_name='Предел (диапазон измерений)')),
                ('period_poverk', models.TextField(blank=True, null=True, verbose_name='Периодичность поверки')),
                ('category_si', models.TextField(blank=True, null=True, verbose_name='Категория СИ')),
                ('organ_poverk', models.TextField(blank=True, null=True, verbose_name='Орган, осуществляющий поверку / Иная инф.')),
                ('data_poverk', models.DateField(blank=True, null=True, verbose_name='Дата последней поверки (месяц/год)')),
                ('srok_poverk', models.DateField(blank=True, null=True, verbose_name='Сроки проведения поверки (месяц/год)')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('conditions', models.JSONField(default=list, verbose_name='Условия отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ManyToManyField(related_name='groups', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Группа оборудования',
                'verbose_name_plural': 'Группы оборудования',
            },
        ),
    ]
