# Generated by Django 5.1.5 on 2025-02-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.TextField(choices=[('measurement_tool', 'Средство измерения'), ('testing_equipment', 'Испытательное оборудование'), ('auxiliary_equipment', 'Вспомогательное оборудование')], default='measurement_tool', verbose_name='Тип оборудования'),
        ),
    ]
