# Generated by Django 5.1.5 on 2025-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='data_poverk',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата последней поверки (месяц/год)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='srok_poverk',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Сроки проведения поверки (месяц/год)'),
        ),
    ]
