# Generated by Django 5.1.5 on 2025-02-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_data_poverk_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipment',
            name='equipment_e_equipme_ce5345_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='equipment_e_name_8baf3a_idx',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='kol_vo',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Кол-во'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type', 'name'], name='equipment_e_equipme_62c16a_idx'),
        ),
    ]
