# Generated by Django 5.1.5 on 2025-02-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_equipment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-id'], 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AddField(
            model_name='equipmentgroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('СИ', 'СИ'), ('ИО', 'ИО'), ('ВО', 'ВО')], max_length=2, verbose_name='Тип оборудования'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='equipment_e_equipme_ce5345_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='equipment_e_name_8baf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['srok_poverk'], name='equipment_e_srok_po_b1ce13_idx'),
        ),
    ]
