# Generated by Django 5.1.5 on 2025-02-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipment_equipment_e_equipme_ce5345_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('СИ', 'СИ'), ('ИО', 'ИО'), ('ВО', 'ВО'), ('РМ', 'РМ')], max_length=2, verbose_name='Тип оборудования'),
        ),
    ]
