# Generated by Django 5.1.5 on 2025-03-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_add_unique_zav_nomer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('zav_nomer__in', ['', '-', 'б/н']), _negated=True), models.Q(('zav_nomer__isnull', True), _negated=True)), fields=('zav_nomer',), name='unique_zav_nomer'),
        ),
    ]
