# Generated by Django 5.1.5 on 2025-02-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=17)),
                ('registration_number', models.CharField(max_length=20)),
                ('engine_number', models.CharField(max_length=50)),
                ('chassis_number', models.CharField(max_length=50)),
                ('body_number', models.CharField(max_length=50)),
                ('engine_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('engine_power', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электро'), ('hybrid', 'Гибрид')], max_length=20)),
                ('max_mass', models.IntegerField()),
                ('unladen_mass', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(choices=[('1', 'Протокол измерений'), ('2', 'Протокол испытаний')], max_length=1, verbose_name='Тип протокола')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='protocols/docx/%Y/%m/%d/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='protocols/pdf/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='vehicles.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'protocol_type')},
            },
        ),
    ]
