# Generated by Django 5.1.5 on 2025-02-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleProtocol',
        ),
    ]
