# Generated by Django 5.1.5 on 2025-01-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='equipment_group',
        ),
    ]
