# Generated by Django 5.1.5 on 2025-02-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('vehicles', '0002_delete_vehicleprotocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_number',
            field=models.CharField(max_length=50, verbose_name='Номер кузова'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(max_length=50, verbose_name='Номер шасси'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(max_length=50, verbose_name='Номер двигателя'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_power',
            field=models.IntegerField(verbose_name='Мощность двигателя (л.с.)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_volume',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем двигателя (л)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электро'), ('hybrid', 'Гибрид')], max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='max_mass',
            field=models.IntegerField(verbose_name='Максимально допустимая масса (кг)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=20, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='unladen_mass',
            field=models.IntegerField(verbose_name='Снаряженная масса (кг)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
