# Generated by Django 5.1.5 on 2025-02-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehiclephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(choices=[('1', 'Протокол измерений'), ('2', 'Протокол испытаний')], max_length=1, verbose_name='Тип протокола')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='protocols/docx/%Y/%m/%d/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='protocols/pdf/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='vehicles.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'protocol_type')},
            },
        ),
    ]
