# Generated by Django 5.1.5 on 2025-02-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_options_remove_vehicle_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_address', models.TextField(blank=True, null=True, verbose_name='Адрес проведения испытаний')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Дата проведения испытаний')),
                ('temperature', models.TextField(blank=True, null=True, verbose_name='Температура воздуха')),
                ('humidity', models.TextField(blank=True, null=True, verbose_name='Относительная влажность')),
                ('pressure', models.TextField(blank=True, null=True, verbose_name='Атмосферное давление')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Иная информация')),
                ('additional_info_two', models.TextField(blank=True, null=True, verbose_name='Дополнительные сведения')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testdata_set', to='vehicles.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='test_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_data', to='vehicles.testdata'),
        ),
    ]
