# Generated by Django 5.1.5 on 2025-02-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_remove_vehicle_actual_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='СustomerData',
            new_name='CustomerData',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='customerData',
            new_name='customer_data',
        ),
    ]
