# Generated by Django 5.1.5 on 2025-02-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_rename_сustomerdata_customerdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='customer_data',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='test_data',
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_data', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='vehicles.vehicle'),
        ),
    ]
