# Generated by Django 5.1.5 on 2025-02-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_remove_vehicle_customer_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='Идентификационный номер (VIN)'),
        ),
    ]
