# Generated by Django 5.1.5 on 2025-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_alter_vehicle_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='custom_info',
            field=models.TextField(blank=True, max_length=500, verbose_name='Заказчик'),
        ),
    ]
