# Generated by Django 5.1.5 on 2025-02-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_vehicle_manufacture_month_vehicle_manufacture_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='manufacture_date',
        ),
    ]
