# Generated by Django 5.1.5 on 2025-02-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_remove_vehicle_manufacture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='manufacture_month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], null=True, verbose_name='Месяц выпуска'),
        ),
    ]
