# Generated by Django 5.1.5 on 2025-02-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_alter_vehicle_manufacture_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, unique=True, verbose_name='Идентификационный номер (VIN)'),
        ),
    ]
