# Generated by Django 5.1.5 on 2025-02-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_alter_vehicle_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Идентификационный номер (VIN)'),
        ),
    ]
