# Generated by Django 5.1.5 on 2025-02-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_remove_testdata_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='humidity_indoor',
            field=models.FloatField(blank=True, null=True, verbose_name='Относительная влажность воздуха в помещении, %'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='humidity_indoor_open',
            field=models.FloatField(blank=True, null=True, verbose_name='Относительная влажность воздуха в помещении с открытыми воротами, %'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='humidity_road',
            field=models.FloatField(blank=True, null=True, verbose_name='Относительная влажность воздуха при проведении испытаний на дороге, %'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='pressure_indoor',
            field=models.FloatField(blank=True, null=True, verbose_name='Атмосферное давление в помещении, кПа'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='pressure_indoor_open',
            field=models.FloatField(blank=True, null=True, verbose_name='Атмосферное давление в помещении с открытыми воротами, кПа'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='pressure_road',
            field=models.FloatField(blank=True, null=True, verbose_name='Атмосферное давление при проведении испытаний на дороге, кПа'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='temperature_indoor',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура воздуха в помещении, °С'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='temperature_indoor_open',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура воздуха в помещении с открытыми воротами, °С'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='temperature_road',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура воздуха при проведении испытаний на дороге, °С'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='tire_pressure_front_left',
            field=models.FloatField(blank=True, null=True, verbose_name='Давление в шине (переднее левое) кПа'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='tire_pressure_front_right',
            field=models.FloatField(blank=True, null=True, verbose_name='Давление в шине (переднее правое) кПа'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='tire_pressure_rear_left',
            field=models.FloatField(blank=True, null=True, verbose_name='Давление в шине (заднее левое) кПа'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='tire_pressure_rear_right',
            field=models.FloatField(blank=True, null=True, verbose_name='Давление в шине (заднее правое) кПа'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer_name',
            field=models.TextField(blank=True, max_length=200, verbose_name='Наименование изготовителя'),
        ),
    ]
