# Generated by Django 5.1.5 on 2025-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_alter_testdata_humidity_indoor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='protocol_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Уникальный номер протокола'),
        ),
    ]
