# Generated by Django 5.1.5 on 2025-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_testdata_protocol_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdata',
            name='protocol_number',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='protocol_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Уникальный номер протокола'),
        ),
    ]
